# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

flutter_application_path = '../flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'ios_host_app' do
  # Use dynamic frameworks for Flutter
  use_frameworks!

  # Pods for ios_host_app
  install_all_flutter_pods(flutter_application_path)
  
end

post_install do |installer|
  flutter_post_install(installer)
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
    end
  end
end

